/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as ApiToursRouteImport } from './routes/api.tours'
import { Route as ApiToursTourIdRouteImport } from './routes/api.tours.$tourId'
import { Route as ToursTourIdChaptersChapterIdRouteImport } from './routes/tours.$tourId.chapters.$chapterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToursRoute = ApiToursRouteImport.update({
  id: '/api/tours',
  path: '/api/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToursTourIdRoute = ApiToursTourIdRouteImport.update({
  id: '/$tourId',
  path: '/$tourId',
  getParentRoute: () => ApiToursRoute,
} as any)
const ToursTourIdChaptersChapterIdRoute =
  ToursTourIdChaptersChapterIdRouteImport.update({
    id: '/chapters/$chapterId',
    path: '/chapters/$chapterId',
    getParentRoute: () => ToursTourIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/tours': typeof ApiToursRouteWithChildren
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/api/tours/$tourId': typeof ApiToursTourIdRoute
  '/tours/$tourId/chapters/$chapterId': typeof ToursTourIdChaptersChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/tours': typeof ApiToursRouteWithChildren
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/api/tours/$tourId': typeof ApiToursTourIdRoute
  '/tours/$tourId/chapters/$chapterId': typeof ToursTourIdChaptersChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/tours': typeof ApiToursRouteWithChildren
  '/tours/$tourId': typeof ToursTourIdRouteWithChildren
  '/api/tours/$tourId': typeof ApiToursTourIdRoute
  '/tours/$tourId/chapters/$chapterId': typeof ToursTourIdChaptersChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/tours'
    | '/tours/$tourId'
    | '/api/tours/$tourId'
    | '/tours/$tourId/chapters/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/tours'
    | '/tours/$tourId'
    | '/api/tours/$tourId'
    | '/tours/$tourId/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/api/tours'
    | '/tours/$tourId'
    | '/api/tours/$tourId'
    | '/tours/$tourId/chapters/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiToursRoute: typeof ApiToursRouteWithChildren
  ToursTourIdRoute: typeof ToursTourIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tours': {
      id: '/api/tours'
      path: '/api/tours'
      fullPath: '/api/tours'
      preLoaderRoute: typeof ApiToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tours/$tourId': {
      id: '/api/tours/$tourId'
      path: '/$tourId'
      fullPath: '/api/tours/$tourId'
      preLoaderRoute: typeof ApiToursTourIdRouteImport
      parentRoute: typeof ApiToursRoute
    }
    '/tours/$tourId/chapters/$chapterId': {
      id: '/tours/$tourId/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/tours/$tourId/chapters/$chapterId'
      preLoaderRoute: typeof ToursTourIdChaptersChapterIdRouteImport
      parentRoute: typeof ToursTourIdRoute
    }
  }
}

interface ApiToursRouteChildren {
  ApiToursTourIdRoute: typeof ApiToursTourIdRoute
}

const ApiToursRouteChildren: ApiToursRouteChildren = {
  ApiToursTourIdRoute: ApiToursTourIdRoute,
}

const ApiToursRouteWithChildren = ApiToursRoute._addFileChildren(
  ApiToursRouteChildren,
)

interface ToursTourIdRouteChildren {
  ToursTourIdChaptersChapterIdRoute: typeof ToursTourIdChaptersChapterIdRoute
}

const ToursTourIdRouteChildren: ToursTourIdRouteChildren = {
  ToursTourIdChaptersChapterIdRoute: ToursTourIdChaptersChapterIdRoute,
}

const ToursTourIdRouteWithChildren = ToursTourIdRoute._addFileChildren(
  ToursTourIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiToursRoute: ApiToursRouteWithChildren,
  ToursTourIdRoute: ToursTourIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
